name: Action Workflow 1
run-name: ${{ github.actor }} testing
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running gh actions workflow"
      - run: echo "${{ github.event }} called from event"
      - run: echo "${{ runner.os }}"
